<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);SYSLIB0050</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);SYSLIB0050</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nintenlord\Nintenlord\Nintenlord.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.5" />
  </ItemGroup>

</Project>
